"""
Insert or update ConSo platform config rows in the CASS PostgreSQL database.

PostgreSQL credentials are read from s3://dash-dbcenter/config/conso/cass_config.json.

Modes
-----
upsert (default)
    Insert or update config rows for the given platform + prefixes.
    --email is required in this mode.

    poetry run python cass_insert.py \\
        --id-platform DRD \\
        --prefixes US,CA \\
        --email engineer@dashmote.com \\
        [--table-list '["outlet_information","outlet_meal","meal_option"]'] \\
        [--finder-concurrent 1] \\
        [--detail-concurrent 16] \\
        [--finder-delay 60] \\
        [--detail-delay 0.1] \\
        [--finder-geo-distance 3000_grid] \\
        [--verify]

activate  (--activate flag)
    Set is_active fields to True for the given rows.
    By default both finder and detail are activated. Use --finder-only or
    --detail-only to activate a single spider when the other is not yet ready.

    poetry run python cass_insert.py \\
        --id-platform DRD \\
        --prefixes US,CA \\
        --activate \\                  # activates both
        [--finder-only] \\             # activates finder only
        [--detail-only] \\             # activates detail only
        [--verify]
"""

import json
import boto3
import psycopg2
import argparse
import pandas as pd


def load_pg_config() -> dict:
    s3 = boto3.client('s3', region_name='eu-central-1')
    raw = s3.get_object(Bucket='dash-dbcenter', Key='config/conso/cass_config.json')['Body'].read()
    return json.loads(raw)


def get_conn_string(cfg: dict) -> str:
    return (
        f"host={cfg['host']} dbname={cfg['dbname']} "
        f"user={cfg['user']} password={cfg['password']} port={cfg['port']}"
    )


# config_id, finder_port, detail_port are omitted — auto-generated by the DB.
# Columns with safe defaults (finder_is_active, detail_is_active, etc.) are also
# omitted here; they stay at their DB defaults until explicitly set via --activate.
UPSERT_SQL = """
    INSERT INTO conso_config (
        id_platform, country_code,
        finder_concurrent_requests, finder_delay, finder_geo_distance,
        detail_concurrent_requests, detail_delay,
        table_list, maintainer_email
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (id_platform, country_code) DO UPDATE SET
        finder_concurrent_requests   = EXCLUDED.finder_concurrent_requests,
        finder_delay                 = EXCLUDED.finder_delay,
        finder_geo_distance          = EXCLUDED.finder_geo_distance,
        detail_concurrent_requests   = EXCLUDED.detail_concurrent_requests,
        detail_delay                 = EXCLUDED.detail_delay,
        table_list                   = EXCLUDED.table_list,
        maintainer_email             = EXCLUDED.maintainer_email,
        last_refresh                 = CURRENT_TIMESTAMP
"""

ACTIVATE_BOTH_SQL = """
    UPDATE conso_config
       SET finder_is_active = TRUE,
           detail_is_active = TRUE,
           last_refresh     = CURRENT_TIMESTAMP
     WHERE id_platform  = %s
       AND country_code = %s
"""

ACTIVATE_FINDER_SQL = """
    UPDATE conso_config
       SET finder_is_active = TRUE,
           last_refresh     = CURRENT_TIMESTAMP
     WHERE id_platform  = %s
       AND country_code = %s
"""

ACTIVATE_DETAIL_SQL = """
    UPDATE conso_config
       SET detail_is_active = TRUE,
           last_refresh     = CURRENT_TIMESTAMP
     WHERE id_platform  = %s
       AND country_code = %s
"""


def main():
    parser = argparse.ArgumentParser(description='Insert/update CASS conso_config rows.')
    parser.add_argument('--id-platform',         required=True)
    parser.add_argument('--prefixes',             required=True, help='Comma-separated, e.g. US,CA')
    parser.add_argument('--email',                dest='maintainer_email', default=None)
    parser.add_argument('--table-list',
                        default='["outlet_information","outlet_meal","meal_option","option_relation"]')
    parser.add_argument('--finder-concurrent',    type=int, default=1)
    parser.add_argument('--detail-concurrent',    type=int, default=16)
    parser.add_argument('--finder-delay',         type=float, default=60)
    parser.add_argument('--detail-delay',         type=float, default=0.1)
    parser.add_argument('--finder-geo-distance',  default='',
                        help='key_suffix from push_grids CONFIGS (e.g. 3000_grid)')
    parser.add_argument('--activate',             action='store_true',
                        help='Set is_active field(s) to True (default: both)')
    parser.add_argument('--finder-only',          action='store_true',
                        help='With --activate: set finder_is_active only')
    parser.add_argument('--detail-only',          action='store_true',
                        help='With --activate: set detail_is_active only')
    parser.add_argument('--verify',               action='store_true',
                        help='Print rows after operation')
    args = parser.parse_args()

    if args.finder_only and args.detail_only:
        parser.error("--finder-only and --detail-only are mutually exclusive")

    prefixes = [p.strip() for p in args.prefixes.split(',')]
    cfg = load_pg_config()
    conn_string = get_conn_string(cfg)

    if args.activate:
        if args.finder_only:
            sql, label = ACTIVATE_FINDER_SQL, 'finder_is_active'
        elif args.detail_only:
            sql, label = ACTIVATE_DETAIL_SQL, 'detail_is_active'
        else:
            sql, label = ACTIVATE_BOTH_SQL, 'finder_is_active + detail_is_active'

        rows = [(args.id_platform, prefix) for prefix in prefixes]
        with psycopg2.connect(conn_string) as conn:
            with conn.cursor() as cur:
                cur.executemany(sql, rows)
            conn.commit()
        print(f"Activated [{label}] for {len(rows)} row(s): {args.id_platform} {prefixes}")

    else:
        if not args.maintainer_email:
            parser.error("--email is required in upsert mode")

        rows = [
            (
                args.id_platform, prefix,
                args.finder_concurrent, args.finder_delay, args.finder_geo_distance,
                args.detail_concurrent, args.detail_delay,
                args.table_list, args.maintainer_email,
            )
            for prefix in prefixes
        ]
        with psycopg2.connect(conn_string) as conn:
            with conn.cursor() as cur:
                cur.executemany(UPSERT_SQL, rows)
            conn.commit()
        print(f"Upserted {len(rows)} row(s) for {args.id_platform}: {prefixes}")

    if args.verify:
        with psycopg2.connect(conn_string) as conn:
            df = pd.read_sql(
                "SELECT id_platform, country_code, finder_is_active, detail_is_active, "
                "finder_geo_distance, maintainer_email, last_refresh "
                f"FROM conso_config WHERE id_platform = '{args.id_platform}'",
                conn
            )
        print(df.to_string())


if __name__ == '__main__':
    main()
